version: '3'
services:

## APLICAÇÃO
  sanboxapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanboxapp
    container_name: sanboxapp
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./:/var/www

## WEBSERVER
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "9000:80"
    networks:
      - backend
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - sanboxapp

## BANCO DE DADOS
  database:
      build:
        context: .
        dockerfile: Dockerfile_Mysql
      container_name: database
      command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
      tty: true
      environment:
        MYSQL_ROOT_PASSWORD: rootpw
      ports:
        - "9001:3306"
      networks:
        - backend
      restart: always
      working_dir: /var/lib/mysql
      volumes:
        - "./docker/database/db:/var/lib/mysql"

      depends_on:
        - sanboxapp

# PHP MYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '9002:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: rootpw
    networks:
      - backend
    depends_on:
      - sanboxapp
      - database
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge